spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sydneyhelperdb?serverTimezone=UTC
    username: root
    password: 123qwe

  jpa:
    show-sql: true